import os

CLIENT_ID = os.environ['VUIIT_CLIENT_ID']
CLIENT_SECRET = os.environ['VUIIT_CLIENT_SECRET']
REDIRECT_URI = os.environ['VUIIT_REDIRECT_URI']
SECRET_KEY = os.environ['VUIIT_SECRET_KEY']
SQLALCHEMY_DATABASE_URI = os.environ['VUIIT_SQLALCHEMY_URI']